cloud:
  aws:
    credentials:
      access-key: AKIA6KZTVXHXDZEZLFF6
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: s3storageprogramfromspring

spring:
  servlet:
    multipart:
      enabled: true
      fileSizeThreshold: 2MB
      maxFileSize: 5MB
      maxRequestSize: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: pawan
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

myapp:
  file-upload:
#    storage-location: /path/to/storage/directory
#    allowed-file-extensions:
#      - png
#      - jpg
#      - jpeg
#      - pdf
#      - doc
#      - docm
#      - docx
#
#    folder-configuration:
#      png: /path/to/storage/directory/png
#      jpg: /path/to/storage/directory/jpg
#      jpeg: /path/to/storage/directory/jpeg
#      pdf: /path/to/storage/directory/pdf
#      doc: /path/to/storage/directory/docs
#      docm: /path/to/storage/directory/docs
#      docx: /path/to/storage/directory/docs

    database-configuration:
      enabled: true
      table-name: file_metadata

server:
  port: 9091
